### ISSUE TITLE
Seawater example of big system does not return any results

### ISSUE THREAD

**Issue by kolmank** [mlund/faunus#98] opened 2017-12-07 10:25 UTC
I tried to simulate a concentrated solution of ions using modified seawater example. To do it I divided the simulation into few steps: 1) equilibration using Weeks-Chandler-Andersen potential (to avoid overlaps of particles) 2) equilibration using Coulomb hard sphere potential 3) production run using Coulomb hard sphere potential. When I try to perform such simulations for small system (cuboid 10 nm, around 600 particles), it works properly. It doesn't work for similar system but 8 times bigger (cuboid 20 nm, around 4800 particles). I have no idea what may cause this issue. Please find attached the bash script used to run simulation and source code of programs to run equilibration and production runs.
[seawater_example.zip](https://github.com/mlund/faunus/files/1538659/seawater_example.zip)

**Comment by bearnix** [comment] 2017-12-07 11:29
Do you have any output from your working small simulation and the larger that failed?

**Comment by kolmank** [comment] 2017-12-07 11:39
Yes, of course. Please find attached the output files (slurm outputs).
[output.zip](https://github.com/mlund/faunus/files/1538883/output.zip)

**Comment by mlund** [comment] 2017-12-07 13:47
Here's a slightly improved cpp but the problem persists. Excessive / unneeded loops in the energy calculation?

[equilibrate.cpp.zip](https://github.com/mlund/faunus/files/1539289/equilibrate.cpp.zip)

**Comment by kolmank** [comment] 2017-12-08 07:41
Mikael, thank you very much for the improved version. I see that you combined both of the codes into one but how do you use only one of the potentials from the potential pair? Do you declare it through an input file?
I have been testing more the issue and actually it is calculating but very slowly. For the big system (around 4800 particles), it took 2 days to finish 1000 steps long equilibtration step. I have also started simulation having 2400 particles (lets call it medium system), here it takes around 5 h to complete the equilibration step. Please find attached the output files.
[output.zip](https://github.com/mlund/faunus/files/1541845/output.zip)

**Comment by mlund** [comment] 2017-12-08 08:07
Unfortunately pair potentials must be set at compile time, but you could use `#ifdef` as done in for example the `water2.cpp` example. I suspect the energy calculation is calculating unneeded interactions. A first step to figure this out is to inspect `_energyChange()` in `Move::AtomTranslate` found in the `move.h` header file.

**Comment by kolmank** [comment] 2017-12-12 10:05
I have continued to test this issue and I see some strange behavior. I prepared new system having around 2400 particles but this time all particles are monovalent ions, I also decreased the box size to 100. Such simulation was finished after only 30 h (please find attached the input and output files). Simulation having similar amount of particles but of the old system  has been ruining for 4 days and still not finished. I assume that box size does not affect the simulation time so the only differences are the properties of particles and that we have only 2 groups of particles.
 
[files_new_system.zip](https://github.com/mlund/faunus/files/1551073/files_new_system.zip)

**Comment by mlund** [comment] 2017-12-13 10:07
I still haven't had time to check the energy evaluation routine. Is there a particular reason for the high number of particles? We have a new version of the program, and once I implement the widom analysis I suggest you give that a try.

**Comment by kolmank** [comment] 2017-12-13 10:24
I can't wait to give a try to the new version of seawater! Actually there are two reasons, the first one is that we are testing some solution where two salts have very different concentration (cement), if the number of particles is lower then we have only 4-5 particles of the salt having lower concentration. The second reason is that we have a lot of old data which was obtained using your fortran code called bulk, since we can not compile it because new gfortran does not support properly f77 we try to use faunus instead. To do some benchmarking we just repeat some of the simulations performed earlier using the fortran code.

**Comment by bearnix** [comment] 2017-12-13 10:49
Hehe, bulk... that old hack ;)

I just remembered that there is actually in some version with weird performance issue in some circumstances with the actual related to the size of the box. It was a long time ago since I noticed it but I thought that was swept out...

Something with the implementation of the minimum image convention if I'm not just remembering some strange dream... Believe I noticed it during a lab with students, calculating activity coefficients of saltwater...

Change geometry to a sphere to check if that would be the case.

/B

**Comment by bearnix** [comment] 2017-12-13 10:49
Pardon my grammar :P

**Comment by kolmank** [comment] 2017-12-13 11:55
Do you mean to try to run the seawater example using sphere geometry?

By the way, is there any possibility to compile the bulk fortran code on newer machines? I have been trying so many different compilers but without any success...

**Comment by bearnix** [comment] 2017-12-13 12:21
Compiling bulk should not be a problem. Eons since I did it but it is just standard fortran code as I remember. But it could be dependent on some library of course.

Yes, use a spherical geometry. 

/B

**Comment by kolmank** [comment] 2017-12-14 11:49
I did the change as you suggested and I think you were right. When I change the geometry to sphere (no pbc), 1000 steps long equilibration finishes in 43 min. The same system in cuboid geometry (same type and amount of particles and same volume) needs more than 4 hours.

**Comment by bearnix** [comment] 2017-12-14 15:01
For a last comparison try to increase the dimensions of the spherical- and cubic(pbc) system and see if the timing changes, keeping everything else constant.

**Comment by mlund** [comment] 2017-12-15 07:00
The output contains relative times for the moves and analysis. Could you check how these differ between the sphere and cuboid? (I assume that the sphere vs. cube was done in Faunus) A factor of four is unreasonable and could be due to for example a virtual function being called more than it should.

**Comment by kolmank** [comment] 2017-12-15 07:17
Mikael, please find below the values. I also attach whole outputs if you need more information.
Sphere geometry:
..........................................
  Markov Move: Single Particle Translation
 ******************************************
  Number of trials              778445
  Relative time consumption     0.999945
  Acceptance                    76.6299﹪
  Runfraction                   100﹪
  Total energy change           -2.47005e+11 kT
  Average moves/particle        443
  Displacement vector           1 1 1

Cuboid geometry:
..........................................
  Markov Move: Single Particle Translation
 ******************************************
  Number of trials              785442
  Relative time consumption     0.999618
  Acceptance                    89.5773﹪
  Runfraction                   100﹪
  Total energy change           -9.99682e+08 kT
  Average moves/particle        446
  Displacement vector           1 1 1

Bearnix, I just started the simulations so I will let you know as soon as they finish.

[cuboid.txt](https://github.com/mlund/faunus/files/1561892/cuboid.txt)
[sphere.txt](https://github.com/mlund/faunus/files/1561893/sphere.txt)

**Comment by bearnix** [comment] 2017-12-15 07:54
First and formost you should see it as to inform yourself :) I could very well be remembering a faulty first interpretation of my own or some confused and corrupt recollection. Simply put, beware of my statements. They are likely wrong. Mikaels suggestion is more reasonable. 

That said, I'm quite confident that I have tread the very same path that you are on before and it is solvable.

/B

**Comment by mlund** [comment] 2017-12-15 08:11
Thanks for the advise Bearnix - we share the recollection :-) I did a test on the `bulk.cpp` example with 2300 particles, altered to a simply Coulomb+WCA potential, no cutoff, no analysis, no volume moves. These are my timings when compiling in release mode:

System  |  secs
-------- | --------
Cuboid  | 29.6
Sphere | 24
Cuboid w. no PBC | 23.8

The interesting question is why your timings differ 4-5 times with and without minimum image? CPU architecture, the compiler?

**Comment by bearnix** [comment] 2017-12-15 08:20
Are you using standard compiler flags for production code? Is debug disabled?

Oh, even a fancy table mlund! Looks solid.

**Comment by kolmank** [comment] 2017-12-15 09:44
Hmmm... In my case I use our cluser Hebbe. I just created new directory, coopied the cpp file, created CMakeList and run following command from main faunus directory:
CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake . -DMYPLAYGROUND=/c3se/users/kolman/Hebbe/faunus/seawater
ant then I go to seawater directory and just write make. I get some warnings but it compiles.

**Comment by mlund** [comment] 2017-12-15 13:15
The minimum image routine is defined in `geometry.h` in the function `Cuboid::sqdist`. Have a look and you'll find that there is an alternative version (uncommented code). Try to use that instead of the current Eigen base routine (which may be sensitive to architecture optimization).

**Comment by kolmank** [comment] 2017-12-15 16:02
Ok, so after increasing the length/radius of cuboid/sphere to double of the initial values, I do not observe any change in simulation time.
Mikael, thank you for the suggestion. I will give it a try.

**Comment by mlund** [comment] 2017-12-16 09:56
Yes, the simulation time should be independent of volume for constant N (and it is for the `bulk.cpp` example). When running on your cluster, could it be that the CPU is affected by other users on the same node? In the queuing system there's often an _exclusive access_ option that will excluded other users from your requested node. You could also try running a 1/2 minute job on the frontend to see if the sphere/cube difference persists.

**Comment by kolmank** [comment] 2017-12-16 13:38
I try to do the changes you suggested  in geometry.h in the function Cuboid::sqdist so after changes it looks like this.
            // Point d = (a - b).cwiseAbs();
            // for ( int i = 0; i < 3; ++i )
            //     if ( d[i] > len_half[i] )
            //         d[i] -= 2 * len_half[i];
            // return d.squaredNorm();
            Alternative algorithm:
            Eigen::Vector3d d = a-b;
            Eigen::Vector3i k = (2*d.cwiseProduct(len_inv)).cast<int>();
            return (d-k.cast<double>().cwiseProduct(len)).squaredNorm();

I noticed that the time is better, instead of 4 hours it takes 2.5. I also did some test on my private computer (i7, 16gb ram) and I observe similar behavior to the one on Hebbe.

**Comment by mlund** [comment] 2017-12-21 08:17
I have still been unable to reproduce the time difference between sphere and cuboid. Also, the above code change does give a significant effect. Could you give it a try using the clang compiler?

**Comment by kolmank** [comment] 2018-01-02 07:48
Unfortunately, the clang compiler is not installed on our cluster so I did some test using my local computer. After compiling with clang, the times are better but still not equal to the time obtained using the sphere geometry. Below are the values:
Clang default PBC algorithm: 3h 20 min
Clang alternative PBC algorithm: 2h 00 min
mlund, you mentioned that you could not reproduce the time difference between sphere and cuboid. Was it for `bulk.cpp` or `seawater.cpp`?

**Comment by mlund** [comment] 2018-01-02 10:30
My tests were on `bulk.cpp` but moves and energy calculations are identical to `seawater.cpp`. My suggestion is to perform less steps and compare 2-3 minute runs; removing all analysis functions and try to figure out where the time difference come from.

**Comment by kolmank** [comment] 2018-01-05 07:27
Ok, I did some  test on a code without any analysis functions (please see the attachments). The system is much smaller, it consist of 450 particles (3 groups of particles NaCl, KCl and CaOH2). Below are the times I obtained for cuboid (pbc) and sphere (no pbc):

| System | Time [seconds] |
| --- | --- |
| Cuboid | 215 |
| Cuboid (alternative algorithm) | 127 |
| Sphere | 31 |

I also did tests on a little bit different system, it again consists of 450 particles but only 1 group (NaCl). The results are quite interesting.

| System | Time [seconds] |
| --- | --- |
| Cuboid | 9 |
| Sphere | 2 |

[equilibrate.cpp.zip](https://github.com/mlund/faunus/files/1605814/equilibrate.cpp.zip)

**Comment by mlund** [comment] 2019-06-11 06:05
Closing this; feel free to re-open if needed.

**Closed by mlund** 2019-06-11 06:05 UTC
Labels: enhancement
